#!/usr/bin/env bash
# display messages at nth iteration
i=1
while [ $i -le 20 ]
do
	if [ $i = 4 ]
	then
		echo -e "$i\nbad luck from China"
	elif [ $i = 9 ]
	then
		echo -e "$i\nbad luck from Japan"
	elif [ $i = 17 ]
	then
		echo -e "$i\nbad luck from Italy"
	else
		echo "$i"
	fi
	(( i++ ))
done
