#!/usr/bin/env bash
# check if file exists

file="School"

if [ -e $file ]
then
	echo "School file exists"
	if [ -s $file ]
	then
		echo "School file is no empty"
	else
		echo "School file is empty"
	fi

	if [ -f $file ]
	then
		echo "School is a regular file"
	fi
else
	echo "School file does not exist"
fi
